### ISSUE TITLE
Indexing collections with elasticsearch error creates index run bottleneck

### ISSUE THREAD

**Issue by kcloud** [RockefellerArchiveCenter/scorpio#160]
## Describe the bug
When indexing an collection from Pisces, if there is a reported error from Elasticsearch, the indexing will terminate. This creates an indexing bottleneck.

## To reproduce
Initialize a index task with an error, in our case a date field index error. The date error will be reported from elasticsearch.
This will terminate the existing index run. The next index run will repeat the issue with the same set.

## Expected behavior
Errors should be reported, but the index run should have the opportunity to complete any collections within the run. Errored objects/collections could be removed from the set, or simply point to the next collection/object within the set.

## Error message or screenshots
('1 document(s) failed to index.', [{'index': {'_index': 'default', '_type': '_doc', '_id': 'jveiGLBDDiioHJFu9xpS4U', 'status': 400, 'error': {'type': 'mapper_parsing_exception', 'reason': "failed to parse field [dates.end] of type [date] in document with id 'jveiGLBDDiioHJFu9xpS4U'. Preview of field's value: '0000'", 'caused_by': {'type': 'illegal_argument_exception', 'reason': 'failed to parse date field [0000] with format [yyyy-MM-dd||yyyy-MM||yyyy]', 'caused_by': {'type': 'date_time_parse_exception', 'reason': 'Failed to parse with all enclosed parsers'}}}, 'data': {'uri': '/collections/jveiGLBDDiioHJFu9xpS4U', 'type': 'collection', 'dates': [{'end': '0000', 'type': 'inclusive', 'begin': '0000', 'label': 'creation', 'source': 'archivesspace', 'expression': 'xxx-xxx'}], 'group': {'dates': [{'end': '0000', 'type': 'inclusive', 'begin': '0000', 'label': 'creation', 'source': 'archivesspace', 'expression': 'xxx-xxx'}], 'title': 'Craig Stevens Papers', 'category': 'collection', 'creators': [], 'identifier': '/collections/jveiGLBDDiioHJFu9xpS4U'}, 'level': 'collection', 'title': 'Craig Stevens Papers', 'online': False, 'extents': [{'type': 'linear_feet', 'value': 'xxx'}], 'formats': ['documents'], 'category': 'collection', 'position': 0, 'languages': [{'expression': 'English', 'identifier': 'eng'}], 'external_identifiers': [{'source': 'archivesspace', 'identifier': '...'}]}}}])

## Impact on your work
This prevents the indexing of collection objects as a result of a single instance of bad data.

**Comment by helrond** [comment]
Noting while I have time: this derives from functionality in [rac_es](https://github.com/RockefellerArchiveCenter/rac_es/blob/base/rac_es/documents.py#L197) which raises an exception rather than catching all errors and continuing on with indexing.
